server:
  port: 9091
  servlet:
    context-path: /todo-list
spring:
  datasource:
    url: "jdbc:postgresql://containers-us-west-131.railway.app:5533/railway"
    username: postgres
    password: 4DE4R6qkxWYznNgb1SAy
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false

